module.exports = {
    ROOM_LIST: 'ROOM_LIST',
    CREATE_ROOM: 'CREATE_ROOM',
    VERIFY_USER: 'VERIFY_USER',
    USER_CONNECT: 'USER_CONNECT',
    USER_DISCONNECT: 'USER_DISCONNECT',
    RECEIVE_VALUES: 'RECEIVE_VALUES',
    TYPING: 'TYPING',
    LOGOUT: 'LOGOUT',
}
